// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTErGSLfnObywMV8EV5JfeFYOHf5qC55A',
    appId: '1:539964811200:web:f657762567f77481a8ca25',
    messagingSenderId: '539964811200',
    projectId: 'message-board-app-c8628',
    authDomain: 'message-board-app-c8628.firebaseapp.com',
    storageBucket: 'message-board-app-c8628.firebasestorage.app',
    measurementId: 'G-19V9H5YZV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbXFPmxpSsMOjPZg6qbUKhMZZMUFmDs2M',
    appId: '1:539964811200:android:3f8a3b3b8ca1d1f5a8ca25',
    messagingSenderId: '539964811200',
    projectId: 'message-board-app-c8628',
    storageBucket: 'message-board-app-c8628.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXN2tW6iEG96JuTyoSaff8Ie698Z_IAQg',
    appId: '1:539964811200:ios:fe9b35850f706f70a8ca25',
    messagingSenderId: '539964811200',
    projectId: 'message-board-app-c8628',
    storageBucket: 'message-board-app-c8628.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXN2tW6iEG96JuTyoSaff8Ie698Z_IAQg',
    appId: '1:539964811200:ios:fe9b35850f706f70a8ca25',
    messagingSenderId: '539964811200',
    projectId: 'message-board-app-c8628',
    storageBucket: 'message-board-app-c8628.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTErGSLfnObywMV8EV5JfeFYOHf5qC55A',
    appId: '1:539964811200:web:7a065ceb7855eb47a8ca25',
    messagingSenderId: '539964811200',
    projectId: 'message-board-app-c8628',
    authDomain: 'message-board-app-c8628.firebaseapp.com',
    storageBucket: 'message-board-app-c8628.firebasestorage.app',
    measurementId: 'G-6T3WCPX3K3',
  );
}
